name: ollama-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - ipykernel
      - jupyter
      - ollama
      - numpy
      - torch
      - matplotlib
      - seaborn
      - scikit-learn
      - pandas


# For llama-cpp-python install
# conda activate ollama-env
# pip install scikit-build-core\[pyproject\]
# CMAKE_ARGS="-DLLAMA_METAL=on" pip install llama-cpp-python

# If you want the fancy formatting with panels and colors:
# pip install rich